### ISSUE TITLE
Is it Alive?

### ISSUE THREAD

**Issue by PerminovEugene** [Tom32i/netcode#13]
Hello! I see that that last activity was 2 years ago. Is this project still actual? I want to use it in my game and don't know worth it or not

**Comment by Tom32i** [comment]
Hey @PerminovEugene ! Last activity is from [august 27](https://github.com/Tom32i/netcode/commits/master) atually.
The project is very much alive and ready to use.

If you have any question using it, please tell me so I can improve the documentation of the project :)
